#include "globals.h"

// const strings
const char *help =
  "Please enter a directory holds only the funcwatch results.\nE.g. ./funcwatch_results/. This folder is automatically generated by funcwatch.\n";
const char *return_name = "$return_value"; //this is defined by funcwatch 
const char *parameterids_outputfile = "parameterids.txt";
const char *pickedIOids_outputfile = "pickedIOids.txt";
